#!/bin/bash
set -ex
## PyTables cannot handle separate locations --prefix --exec-prefix
## in its dependencies, so we do not use --exec-prefix

curdir=`pwd`

cd szip
make clean
./configure --prefix=$INSTMACH && \
make && \
make install
cd $curdir


cd hdf5
make clean
./configure --prefix=$INSTMACH && \
make && \
make install
cd $curdir

cd lzo
make clean
./configure --prefix=$INSTMACH --with-pic && \
make && \
make install
#ln -s $INSTMACH/lib/liblzo2.a $INSTMACH/lib/liblzo.a
cd $curdir

#setenv CFLAGS "$CFLAGS -I$INSTMACH/include/lzo"
#setenv CPPFLAGS "$CPPFLAGS -I$INSTMACH/include/lzo"

export LD_RUN_PATH="$LD_RUN_PATH:$INSTMACH/lib"
cd tables
rm -rf build
PYTAB_SETUP_ARGS="--hdf5=$INSTMACH --lzo=$INSTMACH"
python setup.py $PYTAB_SETUP_ARGS build_ext --inplace && \
python setup.py $PYTAB_SETUP_ARGS install --prefix=$INST --exec-prefix=$INSTMACH
#python -c 'import tables; tables.test()'
## commented the above pytables test out:
## before, python -m tables -c 'tables.test()' test just silently did nothing
## then, the code '' worked
## now, it gives ValueError: numpy.dtype does not appear to be the correct type object
## if executed from the interactive interpreter, it works fine

